#!/usr/bin/env bash
#Script that uses case statements

lpr=1
while [ $lpr -le 20 ]
do
echo "$lpr"
    case $lpr in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((lpr++))
done
