#!/usr/bin/env bash
#Script that uses a nested loop

hr=0
while [ $hr -le 12 ]
do
    echo "Hour: $hr"
    mins=1
    while [ $mins -lt 60 ]
    do
	echo "$mins"
	((mins++))
    done
    ((hr++))
done
