#!/usr/bin/env bash
#Script that uses nested if statements

word="school"
if [ -e $word ]
then
    echo "$word file exists"

    if [ -s $word ]
    then
	echo "$word file is not empty"
    else
	echo "$word file is empty"
    fi

    if [ -f $word ]
    then
	echo "$word is a regular file"
    fi
else
    echo "$word file does not exist"
fi
